name: Build and deploy Node.js app to Azure Web App - Allintravel-web-admin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: 'Archive production artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # ZMIANA: Pakujemy tylko to, co jest potrzebne do uruchomienia aplikacji,
          # a nie cały folder z node_modules.
          path: |
            .next
            public
            package.json
            package-lock.json
            next.config.mjs
            
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          # ZMIANA: Artefakt zostanie wypakowany do podfolderu, np. 'artifact'
          path: artifact/
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DCF7B16A7CBC445E9B34C1A668E26AAC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_38AFD21B5E864D7DACA3604A5E53FFA7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_73865B0AB9F440A085084A8FAB8F668E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Allintravel-web-admin'
          slot-name: 'Production'
          # ZMIANA: Wskazujemy na folder z artefaktem, a nie na '.'
          package: artifact/
